### ISSUE TITLE
NullReferenceException in DeadLetterQueue

### ISSUE THREAD

**Issue by drewfreyling** [GlobalX/SbManager#47]
While trying to peak at the dead letter queue we occassionaly get a 500, I'm assuming because `Value` is null.

``` {#errorContents}
Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GSF.BusManager.Models.ViewModelBuilders.QueueMessagesBuilder.b__1(KeyValuePair`2 kvp) in c:\Builds\5\GlobalX\GSF.BusManager.CI\src\src\GSF.BusManager\Models\ViewModelBuilders\QueueMessagesBuilder.cs:line 61
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at GSF.BusManager.Models.ViewModelBuilders.QueueMessagesBuilder.Build(FindQueuedMessages criteria) in c:\Builds\5\GlobalX\GSF.BusManager.CI\src\src\GSF.BusManager\Models\ViewModelBuilders\QueueMessagesBuilder.cs:line 61
   at GSF.BusManager.CQRS.ModelBuilders.ModelCreator.Build[TModel,TCriteria](TCriteria criteria) in c:\Builds\5\GlobalX\GSF.BusManager.CI\src\src\GSF.BusManager\CQRS\ModelBuilders\ModelCreator.cs:line 34
   at GSF.BusManager.Modules.V1.BusManagerModule.<.ctor>b__3a(Object _) in c:\Builds\5\GlobalX\GSF.BusManager.CI\src\src\GSF.BusManager\HttpModules\V1\BusManagerModule.cs:line 41
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.b__3(Object parameters, CancellationToken context)
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)
```

**Comment by drewfreyling** [comment]
Looks like this was very simiar to #44
